# Generated by Django 4.1.7 on 2023-02-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=50)),
                ('mailAddress', models.CharField(max_length=50)),
                ('uSubject', models.CharField(max_length=25)),
                ('uMessage', models.CharField(max_length=300)),
            ],
        ),
    ]
